name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # 2. Semantic release
      - name: Semantic release
        id: semantic
        uses: cycjimmy/semantic-release-action@v6
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3. Restore Unity Cache (optional)
      - name: Restore Unity Cache (optional)
        # if: steps.semantic.outputs.new_release_published == 'true'
        # continue-on-error: true
        uses: actions/cache@v3
        with:
          path: Nyamu.UnityTestProject/Library
          key: Library-Nyamu-StandaloneLinux64
          restore-keys: |
            Library-Nyamu-
            Library-

      # 4. Export UnityPackage (optional)
      - name: Export UnityPackage (optional)
        # if: steps.semantic.outputs.new_release_published == 'true'
        # continue-on-error: true
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2021.3.45f2
          projectPath: Nyamu.UnityTestProject
          buildMethod: ExportUnityPackage.Export
          targetPlatform: StandaloneLinux64
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}


      # 5. Upload UnityPackage to GitHub Release (optional)
      - name: Upload UnityPackage to GitHub Release (optional)
        if: steps.semantic.outputs.new_release_published == 'true'
        # continue-on-error: true
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.semantic.outputs.new_release_version }}
          files: Nyamu.UnityTestProject/Artifacts/dev.polyblank.nyamu-${{ steps.semantic.outputs.new_release_version }}.unitypackage


      # 6. Create upm branch
      - name: Create upm branch
        run: |
          git checkout -- .
          git branch -d upm &> /dev/null || echo upm branch not found
          git subtree split -P "$PKG_ROOT" -b upm
          git checkout upm
          git config --global user.name 'github-bot'
          git config --global user.email 'github-bot@users.noreply.github.com'
          if [[ -d "Samples" ]]; then
            git mv Samples Samples~
            rm -f Samples.meta
            git commit -am "fix: Samples => Samples~"
          fi
          git checkout main -- README.md CHANGELOG.md
          git commit -am "chore: copy README.md and CHANGELOG.md from main"
          git push -f -u origin upm
        env:
          PKG_ROOT: Nyamu.UnityPackage

      # 7. Create upm git tag
      - name: Create upm git tag
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          git tag $TAG upm
          git push origin --tags
        env:
          TAG: upm/v${{ steps.semantic.outputs.new_release_version }}
